Multi instrument downloads
pysat/pysatSpaceWeather pull request #107
Opened 2022-11-29 21:27 UTC by aburrell

# Description

Addresses #1 by creating files for multiple Instruments during a single Instrument download call.  Must be merged for the release after #105.

# Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality
      to not work as expected)
- This change requires a documentation update

# How Has This Been Tested?

Tested locally and with new unit tests.  There is an example in the new documentation that goes through things.

## Test Configuration
* Operating system: OS X Big Sur
* Version number: Python 3.9
* Any details about your local setup that are relevant: develop branch of pysat

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

If this is a release PR, replace the first item of the above checklist with the
release checklist on the pysat wiki:
https://github.com/pysat/pysat/wiki/Checklist-for-Release

2023-03-03 18:18 UTC, jklenzing requested changes
Looks good! Found a bug in the doc example below, as awell as some typos and style stuff.

2023-03-03 18:18 UTC, jklenzing commented on pysatSpaceWeather/tests/test_instruments.py
> +        pysat.params.data['data_dirs'] = [pysatSpaceWeather.test_data_path]
```suggestion
        pysat.params.data['data_dirs'] = [pysatSpaceWeather.test_data_path]
        pysat.params._set_data_dirs(path=pysatSpaceWeather.test_data_path, store=False)
```
recommend using the `store=False` option here.  If a user is running tests and doing something in parallel, their home directory will be rerouted to the test path while these tests are running.

2023-03-03 20:18 UTC, aburrell commented on pysatSpaceWeather/tests/test_instruments.py
> +        pysat.params.data['data_dirs'] = self.saved_path
```suggestion
        pysat.params._set_data_dirs(path=self.saved_path, store=False)
```

2023-03-04 01:01 UTC, jklenzing approved these changes

2023-03-06 13:07 UTC, merged