BUG: avoid certificate experation
pysat/pysatSpaceWeather pull request #144
Opened 2024-07-30 21:17 UTC by aburrell

Avoid certificate expiration by using the `verify` flag set to False.

Addresses an issue identified at APL, where their certificate had expired.

# Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Unit tests

## Test Configuration
* Operating system: OS X Big Sur
* Version number: Python 3.10
* Any details about your local setup that are relevant: develop branch of pysat

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

If this is a release PR, replace the first item of the above checklist with the
release checklist on the pysat wiki:
https://github.com/pysat/pysat/wiki/Checklist-for-Release

2024-07-30 21:19 UTC, aburrell commented
- [ ] fix broken links
- [ ] update intersphinx mapping
- [ ] fix whatever is up with the GA tests

2024-08-13 15:52 UTC, aburrell commented
@jklenzing any idea how I can get the coverage analysis to run?

2024-08-13 15:55 UTC, aburrell commented on pysatSpaceWeather/instruments/methods/f107.py
> +            f107_fill = f107_fill.resample(freq).asfreq()
```suggestion
        f107_fill = f107_fill.resample(freq).ffill()

2024-08-13 17:27 UTC, jklenzing commented
> @jklenzing any idea how I can get the coverage analysis to run?

Here's what is working for pysatSeasons: https://github.com/pysat/pysatSeasons/pull/43

2024-08-13 19:31 UTC, jklenzing requested changes
Make sure the updates to coveralls are included in the pysat_rc.yml

2024-08-14 01:06 UTC, jklenzing commented
```
FAILED pysatSpaceWeather/tests/test_instruments.py::TestInstruments::test_load_w_pad[pad0-inst_dict16] - AssertionError: Padding should have left data and didn't
FAILED pysatSpaceWeather/tests/test_instruments.py::TestInstruments::test_load_w_pad[pad0-inst_dict25] - AssertionError: Padding should have left data and didn't
FAILED pysatSpaceWeather/tests/test_instruments.py::TestInstruments::test_load_w_pad[pad1-inst_dict16] - AssertionError: Padding should have left data and didn't
FAILED pysatSpaceWeather/tests/test_instruments.py::TestInstruments::test_load_w_pad[pad1-inst_dict25] - AssertionError: Padding should have left data and didn't
```
Padding failures throughout

2024-08-14 14:29 UTC, aburrell commented
@jklenzing that was an unlucky timing issue with one of the realtime files.  Reran tests and now have only expected failures.

2024-08-14 14:33 UTC, jklenzing approved these changes

2024-08-14 14:50 UTC, merged